name: GitHub Actions
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true

jobs:
  jobwf:
    runs-on: ubuntu-latest
    steps:
      - name: Print release version
        run: echo "🔎 Input release ${{ github.event.inputs.release }}"
        
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
            ref: refs/heads/main
            fetch-depth: 0

      - name: Print branch
        run: |
          action_hash=$(git rev-parse --short "$GITHUB_SHA")
          action_branch=${GITHUB_REF#refs/heads/}
          git_hash=$(git rev-parse --short HEAD)
          git_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "🔎 Action checkout: $action_branch $action_hash Current checkout: $git_branch $git_hash"

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup NDK
        run: |
          echo $ANDROID_HOME
          echo $JAVA_HOME
          whereis sdkmanager
          sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"

