name: GitHub Actions
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true

jobs:
  jobwf:
    runs-on: ubuntu-latest
    steps:
      - name: Print release version
        run: echo "🔎 Input release ${{ github.event.inputs.release }}"
        
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
            ref: refs/heads/main
            fetch-depth: 0

      - name: Print branch
        run: |
          action_hash=$(git rev-parse --short "$GITHUB_SHA")
          action_branch=${GITHUB_REF#refs/heads/}
          git_hash=$(git rev-parse --short HEAD)
          git_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "🔎 Action checkout: $action_branch $action_hash Current checkout: $git_branch $git_hash"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.9

      - name: Test tool
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy
          chmod +x ./scripts/py1.py
          ./scripts/py1.py
